### ISSUE TITLE
Unable to build cote.

### ISSUE THREAD

**Issue by yogeshmpandey** [CMUAbstract/cote#5]
Hi,

I am trying to build cote but I am always getting stuck at this point. 
I am using Ubuntu 20.04 with kernel version Linux p 5.4.0-65-generic for the install. 

![issue](https://user-images.githubusercontent.com/2559013/107178555-614b5700-69fa-11eb-904d-3079135dfb0b.png)

Can someone help me out here? I think there is some version mismatch.

**Comment by mablem8** [comment]
Hello! Happy to help - could you post the commands leading up to the error? Are you running the `setup_dependencies.sh` script from `cote/scripts/`?

**Comment by yogeshmpandey** [comment]
Yes, I am running the `setup_dependencies.sh` from the `cote/scripts` directory. The build continues for a couple of hours and ends up with the above issue.

**Comment by mablem8** [comment]
I set up a fresh install of Ubuntu 20.04 to make sure the script wasn't missing any dependencies.

There has been some link rot (`wget https://www.mpfr.org/mpfr-current/mpfr-4.0.2.tar.gz` -> `wget https://www.mpfr.org/mpfr-4.0.2/mpfr-4.0.2.tar.gz`), but after fixing I had the same output you posted.

Turns out these errors are not an issue; so long as `gcc-8.3.0-install/bin/` contains `g++`, then the setup script is successful.

One way to test would be:
```
cd cote/examples/generate-ecis/build/
CXX=path/to/gcc-8.3.0-install/bin/g++ cmake ../source/
make
./generate_ecis ../configuration/ ../logs/
```

Be sure to substitute `path/to/gcc-8.3.0-install/bin/g++` with the location of `g++` from the setup script.

If you still have issues with GCC 8.3.0, Ubuntu 20.04 actually pulls version 9.3.0 for `sudo apt install build-essential`. So the following works too:
```
cd cote/examples/generate-ecis/build/
cmake ../source/
make
./generate_ecis ../configuration/ ../logs/
```

**Comment by yogeshmpandey** [comment]
Thanks,

I followed the above steps and able to build and run the sample from the examples directory.

While running the all-params example, I am following these steps: 

- Generate the sample configurations using `setup_sample_configuration_files.sh` and copy them to the configuration folder. 

- Run using the following command : `./all_params ../configuration/ ../logs/`

Please clarify the below points.

- The example is still running for 3+ hours. Is this expected? 

- Is this example replicates the experiments in section 4.2 in the paper?

- Is there a better-detialed documentation about the all-params example, the README.md at [this](https://github.com/CMUAbstract/cote/tree/master/examples) folder has no information about the example?

**Comment by mablem8** [comment]
Apologies for the late reply! This all_params example is a newer example, so it does not correspond to the experiments in the ASPLOS'20 paper. The execution time depends on the time step count, the number of elements simulated, and of course the computer you use. For this example, it is not unexpected to have a longer execution time
